version: 2

project_name: gdatum

env:
  - IMAGE_NAME={{ if index .Env "IMAGE_NAME"  }}{{ .Env.IMAGE_NAME }}{{ else }}ghcr.io/epicstep/gdatum{{ end }}
  - MODULE_NAME=github.com/EpicStep/gdatum

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - main: ./cmd/app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X '{{ .Env.MODULE_NAME }}/internal/utils/buildinfo.binaryVersion=v{{ .Version }}'

archives:
  - formats: [ "tar.gz" ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [ "zip" ]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64"
    dockerfile: Containerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.description=Make game servers stats great again!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64"
    dockerfile: Containerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.description=Make game servers stats great again!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "{{ .Env.IMAGE_NAME }}:v{{ .Version }}"
    image_templates:
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64"
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64"
  - name_template: "{{ .Env.IMAGE_NAME }}:latest"
    image_templates:
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64"
      - "{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

changelog:
  sort: asc
  use: github

