coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        informational: true
    patch:
      default:
        informational: true
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
