services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.5
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_PASSWORD: dev-password
