// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetServer implements getServer operation.
//
// Get server by ID.
//
// GET /multiplayer/{multiplayerName}/server/{serverID}
func (UnimplementedHandler) GetServer(ctx context.Context, params GetServerParams) (r GetServerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMultiplayerSummaries implements listMultiplayerSummaries operation.
//
// Get a summary of multiplayer platforms.
//
// GET /multiplayers/summaries
func (UnimplementedHandler) ListMultiplayerSummaries(ctx context.Context, params ListMultiplayerSummariesParams) (r []MultiplayerSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// ListServerStatistics implements listServerStatistics operation.
//
// Get server statistics by ID.
//
// GET /multiplayer/{multiplayerName}/server/{serverID}/statistics
func (UnimplementedHandler) ListServerStatistics(ctx context.Context, params ListServerStatisticsParams) (r ListServerStatisticsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListServerSummaries implements listServerSummaries operation.
//
// List servers for a multiplayer platform.
//
// GET /multiplayer/{multiplayerName}/servers
func (UnimplementedHandler) ListServerSummaries(ctx context.Context, params ListServerSummariesParams) (r ListServerSummariesRes, _ error) {
	return r, ht.ErrNotImplemented
}
