// Code generated by ogen, DO NOT EDIT.
package api

type GetServerByIDRes interface {
	getServerByIDRes()
}

type GetServerStatisticsByIDRes interface {
	getServerStatisticsByIDRes()
}

type GetServersByMultiplayerRes interface {
	getServersByMultiplayerRes()
}
