// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s GetServerStatisticsByIDOKApplicationJSON) Validate() error {
	alias := ([]ServerStatistic)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s GetServerStatisticsByIDPrecision) Validate() error {
	switch s {
	case "perHour":
		return nil
	case "perDay":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetServersByMultiplayerOKApplicationJSON) Validate() error {
	alias := ([]ServerSummary)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s Order) Validate() error {
	switch s {
	case "asc":
		return nil
	case "desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
