// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetMultiplayersSummaryOperation  OperationName = "GetMultiplayersSummary"
	GetServerByIDOperation           OperationName = "GetServerByID"
	GetServerStatisticsByIDOperation OperationName = "GetServerStatisticsByID"
	GetServersByMultiplayerOperation OperationName = "GetServersByMultiplayer"
)
