openapi: 3.0.2
info:
  version: 1.0.0
  title: Gdatum API
servers:
  - url: 127.0.0.1:8080
    description: Local
tags:
  - name: monitoring
    description: Monitoring of game servers
paths:
  /multiplayers/summary:
    get:
      tags:
        - monitoring
      summary: Get multiplayers summary
      operationId: getMultiplayersSummary
      parameters:
        - name: playersOrder
          in: query
          description: Sort order by current players
          schema:
            $ref: "schemas.yml#/components/schemas/Order"
      responses:
        '200':
          $ref: "responses.yml#/components/responses/GetMultiplayersSummaryOK"
  '/multiplayer/{multiplayerName}/servers':
    get:
      tags:
        - monitoring
      summary: Get servers by multiplayer
      operationId: getServersByMultiplayer
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: playersOrder
          in: query
          description: Sort order by players
          schema:
            $ref: "schemas.yml#/components/schemas/Order"
        - name: count
          in: query
          description: Count of return servers, -1 for all
          schema:
            type: integer
            format: int32
            default: -1
            minimum: -1
        - name: includeOffline
          in: query
          description: Include offline servers or no.
          schema:
            type: boolean
      responses:
        '200':
          $ref: "responses.yml#/components/responses/GetServersByMultiplayerOK"
        '404':
          description: Multiplayer not found
  '/multiplayer/{multiplayerName}/server/{serverID}':
    get:
      tags:
        - monitoring
      summary: Get server by ID
      operationId: getServerByID
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: serverID
          in: path
          description: ID of a server
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: "responses.yml#/components/responses/GetServerByIDOK"
        '404':
          description: Server not found
  '/multiplayer/{multiplayerName}/server/{serverID}/statistics':
    get:
      tags:
        - monitoring
      summary: Get server stats by ID
      operationId: getServerStatisticsByID
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: serverID
          in: path
          description: ID of a server
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: Count of return stats
          schema:
            type: integer
            format: int32
            default: 720
            minimum: 1
            maximum: 720
        - name: lastSeen
          in: query
          description: Show stats after last seen
          schema:
            type: string
            format: date-time
        - name: timeOrder
          in: query
          description: Sort order by collection time
          schema:
            $ref: "schemas.yml#/components/schemas/Order"
        - name: precision
          in: query
          description: Output precision
          schema:
            type: string
            default: perHour
            enum:
              - perHour
              - perDay
      responses:
        '200':
          $ref: "responses.yml#/components/responses/GetServerStatisticsByID"
        '404':
          description: Server not found
