openapi: 3.0.2
info:
  version: 1.0.0
  title: Gdatum API
servers:
  - url: /v1
tags:
  - name: monitoring
    description: Monitoring of game servers
paths:
  /multiplayers/summary:
    get:
      tags:
        - monitoring
      summary: Get multiplayers summary
      operationId: getMultiplayersSummary
      parameters:
        - name: order
          in: query
          description: Sort order by online
          schema:
            type: string
            default: desc
            enum:
              - asc
              - desc
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - online
                  properties:
                    name:
                      type: string
                      description: Name of a multiplayer
                    online:
                      type: integer
                      format: int64
  '/multiplayer/{multiplayerName}/servers':
    get:
      tags:
        - monitoring
      summary: Get servers by multiplayer
      operationId: getServersByMultiplayer
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: Count of return objects, -1 for all
          schema:
            type: integer
            format: int32
            default: -1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - online
                  properties:
                    name:
                      type: string
                    online:
                      type: integer
                      format: int32
        '404':
          description: Multiplayer not found
  '/multiplayer/{multiplayerName}/server/{serverID}':
    get:
      tags:
        - monitoring
      summary: Get server by ID
      operationId: getServerByID
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: serverID
          in: path
          description: ID of a server
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  gamemode:
                    type: string
                  lang:
                    type: string
        '404':
          description: Server not found
  '/multiplayer/{multiplayerName}/server/{serverID}/stats':
    get:
      tags:
        - monitoring
      summary: Get server stats by ID
      operationId: getServerStatsByID
      parameters:
        - name: multiplayerName
          in: path
          description: Name of a multiplayer
          required: true
          schema:
            type: string
        - name: serverID
          in: path
          description: ID of a server
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: Count of return stats
          schema:
            type: integer
            format: int32
            default: 720
            maximum: 720
        - name: after
          in: query
          description: Show stats after time
          schema:
            type: string
            format: date-time
        - name: order
          in: query
          description: Sort order by timestamp
          schema:
            type: string
            default: desc
            enum:
              - asc
              - desc
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - timestamp
                    - online
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    online:
                      type: integer
                      format: int32
        '404':
          description: Server not found
