name: Release
on:
  workflow_dispatch:
    inputs:
      bumpType:
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
        description: Select the version bump type for the release.

permissions:
  contents: write
  checks: write
  packages: write
  id-token: write
  attestations: write

jobs:
  pre-checks:
    name: Run Tests and Linter
    uses: ./.github/workflows/tests-and-lint.yml
  release:
    runs-on: ubuntu-latest
    needs: [ pre-checks ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup cosign
        uses: sigstore/cosign-installer@v3
      - name: Setup syft
        uses: anchore/sbom-action/download-syft@v0.20.6
      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create next tag
        run: |
          ./hack/create-next-tag.sh ${{ github.event.inputs.bumpType }})
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.12.5
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate signed build provenance attestations
        uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: ./dist/checksums.txt
