name: Tests and Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  lint-and-test:
    name: Tests and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 5m
      - name: Tests
        run: go test ./... --timeout 5m -coverprofile=coverage.txt -race
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        if: github.event_name == 'push' || github.event_name == 'pull_request' # don't run on release
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
